---
title: Try, catch blocks
description: Learn about try, catch blocks in Ripple
---

Try blocks work to building the foundation for **error boundaries**, when the runtime encounters
an error in the `try` block, you can easily render a fallback in the `catch` block.

```ripple
import { reportError } from 'some-library';

component ErrorBoundary() {
  <div>
    try {
      <ComponentThatFails /> // throws an error
    } catch (e) {
      reportError(e);

      <div>{"An error occured! " + e.message}</div>
    }
  </div>
}
```